name: ARC test
on:
  workflow_dispatch:

jobs:
  ARC-Test:
    runs-on: arc-runner-set
    steps:
    - run: |
           sudo apt-get update
           sudo apt-get install -y curl
           curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

           # Make kubectl executable
           chmod +x kubectl

           # Move kubectl to a directory in the PATH
           sudo mv kubectl /usr/local/bin/

           # Verify kubectl installation
           kubectl version --client
          
