name: ARC test
on:
  workflow_dispatch:

jobs:
  ARC-Test:
    runs-on: arc-runner-set
    steps:
    - run: |
           wget https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
           
          
