name: ARC test
on:
  workflow_dispatch:

jobs:
  ARC-Test:
    runs-on: arc-runner-set
    steps:

      - name: Install Docker
        run: |
             sudo apt-get update
             sudo apt-get install -y curl
             curl -fsSL https://get.docker.com -o get-docker.sh

             # Run Docker install script
             sudo sh get-docker.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
           push: true
           tags: hegash/mnist-convnet-image:arc-docker-test
