name: ARC test
on:
  workflow_dispatch:

jobs:
  ARC-Test:
    runs-on: arc-runner-set
    steps:
    - run: |
           apt-get update
           sudo apt-get install -y kubectl
           
          
