name: ARC test
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: arc-runner-set
    steps:
    - run: |
           sudo apt-get update
           sudo apt-get install -y kubectl
           kubectl version
