name: Deploy to GKE

on:
  push:
    tags:
      - '*'

jobs:
  deploy-to-gke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: 'mnist-convnet-cluster'
        location: 'us-central1'

    - name: Create mnist-job.yaml
      run: |
           touch mnist-job-test.yaml
           echo "
           apiVersion: "batch/v1"
           kind: "Job"
           metadata:
             name: "mnist-convnet-job-new"
           spec:
            template:
               spec:
                 containers:
                 - name: "mnist-convnet-job-new"
                   image: "hegash/mnist-convnet-image:${{ github.ref_name }}"
                   env:
                   - name: "WANDB_API_KEY"
                     value: "4a2bfc8af55c4761a87469879e6f5c4020ad4a6b"
                 restartPolicy: "Never"" > ~/mnist-job-test.yaml

    - name: Apply Kubernetes Job
      run: kubectl apply -f mnist-job-test.yaml
