name: Deploy to GKE

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-to-gke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: 'mnist-convnet-cluster'
        location: 'us-central1'

    - name: Apply Kubernetes Job
      run: kubectl apply -f mnist-job.yaml
