name: Temp 2

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
           push: true
           tags: hegash/mnist-convnet-image:testing


  deploy-to-gke:
    runs-on: arc-runner-set
    needs: build-and-push
    steps:
    - name: Sleep
      run: sleep 10
    
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: 'mnist-convnet-cluster'
        location: 'us-central1'

    - name: Create mnist-job-testing.yaml
      run: |
           touch mnist-job-testing.yaml
           echo "
           apiVersion: "batch/v1"
           kind: "Job"
           metadata:
             name: "mnist-convnet-job-testing"
           spec:
            template:
               spec:
                 containers:
                 - name: "mnist-convnet-job-testing"
                   image: "hegash/mnist-convnet-image:testing"
                   args: ["--batch_size=12"]
                   env:
                   - name: "WANDB_API_KEY"
                     value: "${{ secrets.WANDB_API_KEY }}"
                 restartPolicy: "Never"" > ~/mnist-job-testing.yaml



    - name: Apply Kubernetes Job
      run: |
           sudo apt-get update
           sudo apt-get install -y curl
           curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

           # Make kubectl executable
           chmod +x kubectl

           # Move kubectl to a directory in the PATH
           sudo mv kubectl /usr/local/bin/
           kubectl apply -f ~/mnist-job-testing.yaml
